<a href="https://colab.research.google.com/github/kmongsil1105/colab_ipynb/blob/main/AI_NLTK%26KoNLpy_%EC%9E%90%EC%97%B0%EC%96%B4_%EC%A0%84%EC%B2%98%EB%A6%AC_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# https://datascienceschool.net/03%20machine%20learning/03.01.02%20KoNLPy%20%ED%95%9C%EA%B5%AD%EC%96%B4%20%EC%B2%98%EB%A6%AC%20%ED%8C%A8%ED%82%A4%EC%A7%80.html

##########################################
# 자연어 처리를 위한 NLTK와 KoNLPy 설치하기
##########################################

!pip3 install nltk   # NLTK(Natural Language Toolkit) 패키지는 교육용으로 개발된 자연어 처리 및 문서 분석용 파이썬 패키지
                     # NLTK 패키지가 제공하는 주요 기능 ==> 말뭉치 / 토큰 생성 / 형태소 분석 / 품사 태깅

#########################################
# konlpy 설치의존성 확인(JDK 설치 필요)
# ! java --version
# 결과 ==>
        # openjdk 11.0.11 2021-04-20
        # OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
        # OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)                   

########################################
# 없으면 JDK 설치
# ! sudo apt install openjdk-13-jdk
# 결과 ==>
        # Reading package lists... Done
        # Building dependency tree       
        # Reading state information... Done
        # E: Unable to locate package openjdk-13-jdk

#######################################
!pip3 install konlpy    # 코엔엘파이(KoNLPy)는 한국어 자연어 처리를 위한 형태소 분석기 패키지
# 실습시마다 매번 할 것!!!

     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 86 kB 5.4 MB/s 
     |████████████████████████████████| 448 kB 46.2 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [ ]:
import nltk
nltk.__version__

'3.2.5'

In [ ]:
import warnings
warnings.simplefilter("ignore")

import konlpy
konlpy.__version__

'0.5.2'

In [ ]:
# KoNLPy에서는 대한민국 헌법 말뭉치인 kolaw와 국회법안 말뭉치인 kobill을 제공한다. 
# 각 말뭉치가 포함하는 파일의 이름은 fields 메서드로 알 수 있고 open 메서드로 해당 파일의 텍스트를 읽어들인다.

from konlpy.corpus import kolaw
kolaw.fileids()


['constitution.txt']

In [ ]:
c = kolaw.open('constitution.txt').read()
print(c[:40])  # 글자수

#
# '아'  ==> 아스키코드(iso8859-1/2/3/4)
#       ==> 완성형(ksc5601-1987 / euc-kr) 2바이트(한글) , 1바이트(영문, 숫자)
#       ==> 유니코드(unicode) 2바이트(영문/한글)
#       ==> UTF-8(변형유니코드) 1바이트(영문, 숫자), 2바이트, 3바이트(한글), 4바이트 가변길이 - 웹사이트에서는 (권고)
#       ==> CP949(윈도우즈 한글표현) -> 완성형과 80% 동일, 20%는 상이

# 한글이 몇자인가? 자소(글자 element) 11,172자 (폰트 한 벌)
#                 --> 완성형이 표준 2350자(1987) --> 4888자 --> 11,172자 

대한민국헌법

유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로


In [ ]:
# KoNLPy에서는 대한민국 헌법 말뭉치인 kolaw와 국회법안 말뭉치인 kobill을 제공한다. 
# 각 말뭉치가 포함하는 파일의 이름은 fields 메서드로 알 수 있고 open 메서드로 해당 파일의 텍스트를 읽어들인다.

from konlpy.corpus import kobill
kobill.fileids()

['1809891.txt',
 '1809895.txt',
 '1809890.txt',
 '1809899.txt',
 '1809893.txt',
 '1809894.txt',
 '1809892.txt',
 '1809898.txt',
 '1809897.txt',
 '1809896.txt']

In [ ]:
d = kobill.open('1809890.txt').read()
print(d[:40])

지방공무원법 일부개정법률안

(정의화의원 대표발의 )

 의 안
 번 호


In [ ]:
# 형태소 분석
#######################
# KoNLPy는 다음과 같은 다양한 형태소 분석, 태깅 라이브러리를 파이썬에서 쉽게 사용할 수 있도록 모아놓았다.

# Hannanum: 한나눔. KAIST Semantic Web Research Center 개발.==> http://semanticweb.kaist.ac.kr/hannanum/
# Kkma: 꼬꼬마. 서울대학교 IDS(Intelligent Data Systems) 연구실 개발.==> http://kkma.snu.ac.kr/
# Komoran: 코모란. Shineware에서 개발.==> https://github.com/shin285/KOMORAN
# Mecab: 메카브. 일본어용 형태소 분석기를 한국어를 사용할 수 있도록 수정. ==> https://bitbucket.org/eunjeon/mecab-ko
# Open Korean Text: 오픈 소스 한국어 분석기. 과거 트위터 형태소 분석기. ==> https://github.com/open-korean-text/open-korean-text
###########################
from konlpy.tag import *
###########################

# mecab = Mecab() # mecab ==> error 발생으로 일단 주석처리...
kkma = Kkma()  # 꼬꼬마
komoran = Komoran()  # 꼬모란

In [ ]:
# 명사 추출
# 문자열에서 명사만 추 출하려면 noun 명령을 사용한다.
# c = kolaw.open('constitution.txt').read()
# print(c[:40])
# 결과 ==> 대한민국헌법
#      ==>  유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로

komoran.nouns("\n".join([s for s in c[:40].split("\n") if s]))

# 대한민국 헌법중에서 명사만 보여준다

['대한민국', '헌법', '역사', '전통', '국민', '운동']

In [ ]:
# c = kolaw.open('constitution.txt').read()
# print(c[:40])
# 결과 ==> 대한민국헌법
#      ==>  유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로

komoran.morphs("\n".join([s for s in c[:40].split("\n") if s]))

# 형태소를 쪼개서 출력한다.

['대한민국',
 '헌법',
 '유구',
 '하',
 'ㄴ',
 '역사',
 '와',
 '전통',
 '에',
 '빛나',
 '는',
 '우리',
 '대하',
 'ㄴ',
 '국민',
 '은',
 '3',
 '·',
 '1',
 '운동',
 '으로']

In [ ]:
# c = kolaw.open('constitution.txt').read()
# print(c[:40])
# 결과 ==> 대한민국헌법
#      ==>  유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로

komoran.pos("\n".join([s for s in c[:40].split("\n") if s]))

# pos 명령을 사용하면 품사 부착을 한다.
# komoran은 빈줄이 있으면 에러가 남

[('대한민국', 'NNP'),
 ('헌법', 'NNP'),
 ('유구', 'XR'),
 ('하', 'XSA'),
 ('ㄴ', 'ETM'),
 ('역사', 'NNG'),
 ('와', 'JC'),
 ('전통', 'NNG'),
 ('에', 'JKB'),
 ('빛나', 'VV'),
 ('는', 'ETM'),
 ('우리', 'NP'),
 ('대하', 'VV'),
 ('ㄴ', 'ETM'),
 ('국민', 'NNP'),
 ('은', 'JX'),
 ('3', 'SN'),
 ('·', 'SP'),
 ('1', 'SN'),
 ('운동', 'NNP'),
 ('으로', 'JKB')]

In [ ]:
###########################################################
# 여기까지 작업하고 
# Mecab() 설치를 위해서 세션종료하고 (메뉴:런타임 -> 세션관리 -> 종료)
# 아래부터 다시 실행!!!   ==>    https://sosomemo.tistory.com/31
##########################################################

In [ ]:
! java -version

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)


In [ ]:
# 형태소 분석 ==> KoNLPy는 다음과 같은 다양한 형태소 분석, 태깅 라이브러리를 파이썬에서 쉽게 사용할 수 있도록 모아놓았다.

 # Mecab: 메카브. 일본어용 형태소 분석기를 한국어를 사용할 수 있도록 수정. ==> https://bitbucket.org/eunjeon/mecab-ko
 ###############################
 # Mecab 설치
 ###############################
!apt-get update
!apt-get install g++ openjdk-11-jdk # java version이 "11.0.11" 이므로
!pip3 install konlpy JPype1-py3
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)


Get:1 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:4 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:11 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [1,794 kB]
Ign:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:13 https://developer.download.nvidia.co

In [ ]:
from konlpy.tag import *
mecab = Mecab()

from konlpy.corpus import kolaw
kolaw.fileids()

c = kolaw.open('constitution.txt').read()

mecab.nouns(c[:40])


['대한민국', '헌법', '역사', '전통', '우리', '국민', '운동']

In [ ]:
mecab.morphs(c[:40])
# 형태소 분석

['대한민국',
 '헌법',
 '유구',
 '한',
 '역사',
 '와',
 '전통',
 '에',
 '빛나',
 '는',
 '우리',
 '대한',
 '국민',
 '은',
 '3',
 '·',
 '1',
 '운동',
 '으로']

In [ ]:
mecab.pos(c[:40])


[('대한민국', 'NNP'),
 ('헌법', 'NNG'),
 ('유구', 'XR'),
 ('한', 'XSA+ETM'),
 ('역사', 'NNG'),
 ('와', 'JC'),
 ('전통', 'NNG'),
 ('에', 'JKB'),
 ('빛나', 'VV'),
 ('는', 'ETM'),
 ('우리', 'NP'),
 ('대한', 'VV+ETM'),
 ('국민', 'NNG'),
 ('은', 'JX'),
 ('3', 'SN'),
 ('·', 'SC'),
 ('1', 'SN'),
 ('운동', 'NNG'),
 ('으로', 'JKB')]

In [ ]:
#########################
# 텍스트 전처리
#########################
# 1. 토큰화(Tokenization)
########################
# NLTK는 영어 코퍼스를 토큰화하기 위한 도구들을 제공합니다. 그 중 word_tokenize

from nltk.tokenize import word_tokenize  
nltk.download("punkt")

print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))  

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
# 토큰화(Tokenization)
# WordPunctTokenizer를 사용해서 NLTK에서는 아포스트로피를 어떻게 처리하는지 확인
from nltk.tokenize import WordPunctTokenizer  
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
# 케라스 또한 토큰화 도구로서 text_to_word_sequence를 지원합니다. 이번에는 케라스로 토큰화를 수행해봅시다.

! pip install keras
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

# keras에서는 아프스트로피(') 처리도 깔끔하게 된다.

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [ ]:
# 문장 토큰화(Sentence Tokenization)

from nltk.tokenize import sent_tokenize
text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print(sent_tokenize(text))

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [ ]:
# 문장 중간에 마침표가 여러번 등장하는 경우에 대해서도 실습

from nltk.tokenize import sent_tokenize
text="I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text))

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
# 한국어에 대한 문장 토큰화 도구 ==> KSS(Korean Sentence Splitter)를 추천

! pip install kss
import kss

text='딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어려워요. 농담아니에요. 이제 해보면 알걸요?'
print(kss.split_sentences(text))

     |████████████████████████████████| 42.3 MB 46 kB/s 
     |████████████████████████████████| 184 kB 63.1 MB/s 
  Created wheel for kss: filename=kss-3.1.0.4-py3-none-any.whl size=42336591 sha256=d9455b03cb7c9096cf9b367be0496041ff557adfae30d0bb607a641f3c69755d
  Stored in directory: /root/.cache/pip/wheels/94/d8/3c/b5f02f814e08c3e2f35e32ae2ac92a34c8412ed6f92ff470ce
  Created wheel for emoji: filename=emoji-1.4.2-py3-none-any.whl size=186469 sha256=c7d1bbcac76826144a999148b19d3710a386fc2dc7cb87f19ed5a35043cbd3f8
  Stored in directory: /root/.cache/pip/wheels/e4/61/e7/2fc1ac8f306848fc66c6c013ab511f0a39ef4b1825b11363b2
Successfully built kss emoji


[Korean Sentence Splitter]: Initializing Kss...


['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어려워요. 농담아니에요.', '이제 해보면 알걸요?']


In [ ]:
#########################
# 텍스트 전처리
#########################
# 2. NLTK에서 불용어 확인하기 ==> 큰 의미가 없는 단어 토큰을 제거하는 작업이 필요
###########################
import nltk
nltk.download('stopwords')
  

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords  
stopwords.words('english')[:10]  # 출력 결과가 100개 이상이기 때문에 여기서는 간단히 10개만 확인

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [ ]:
import nltk
nltk.download('punkt')

from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_tokens = word_tokenize(example)

result = []
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 

print("before==> ",word_tokens) 
print("after==> ",result) 


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
before==>  ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
after==>  ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [ ]:
# 한국어에서 불용어 제거하기
######################
import nltk
nltk.download('punkt')
#######################
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "아무거나 아무렇게나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 하면 삼겹살을 . 아니거든 구우려고 "  # 제거하고 싶은 단어들을 나열
# 위의 불용어는 명사가 아닌 단어 중에서 저자가 임의로 선정한 것으로 실제 의미있는 선정 기준이 아님
stop_words=stop_words.split(' ')
word_tokens = word_tokenize(example)

result = [] 
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 
# 위의 4줄은 아래의 한 줄로 대체 가능
# result=[word for word in word_tokens if not word in stop_words]

print(word_tokens) 
print(result)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '안', '돼', '고기라고', '다', '같은', '게', '구울', '때는', '중요한', '게', '있지']


In [ ]:
#  한국어 전처리 패키지(Text Preprocessing Tools for Korean Text)

!pip3 install customized_konlpy

from ckonlpy.tag import Twitter
okt= Twitter()

okt.add_dictionary('은경이', 'Noun')
okt.morphs('은경이는 사무실로 갔습니다.')


/usr/local/lib/python3.7/dist-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


TypeError: ignored

In [ ]:
#########################
# 텍스트 전처리
#########################
# 한국어 전처리 패키지(Text Preprocessing Tools for Korean Text) 추가!!!
# 3. PyKoSpacing  ==> "정규표현식" 대신 사용 (띄어쓰기를 해 줌)
###########################

# 띄어쓰기가 되어있지 않은 문장을 "띄어쓰기"를 한 문장으로 변환해주는 패키지
!pip3 install git+https://github.com/haven-jeon/PyKoSpacing.git  # PyKoSpacing 설치


sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'

new_sent = sent.replace(" ", '') # 띄어쓰기가 없는 문장 임의로 만들기
print(new_sent)



  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-6qsgba3b
  Running command git clone -q https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-6qsgba3b
     |████████████████████████████████| 454.3 MB 18 kB/s 
     |████████████████████████████████| 1.2 MB 58.5 MB/s 
     |████████████████████████████████| 4.0 MB 59.3 MB/s 
     |████████████████████████████████| 462 kB 69.0 MB/s 
  Created wheel for pykospacing: filename=pykospacing-0.5-py3-none-any.whl size=2255830 sha256=2fee5e6ffec32444618c6fbd8a4e31f5304268541bf72742a693e4b2e57dc431
  Stored in directory: /tmp/pip-ephem-wheel-cache-8ckd19c_/wheels/9b/93/81/a2a7dc8c66ede5bf30634d20635f32b95eac7ca2ea8844058b
Successfully built pykospacing
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.39.0
    Uninstalling grpcio-1.39.0:
      Successfully uninstalled grpcio-1.39.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.


In [ ]:
# 위의 결과를 PyKoSpacing의 입력으로 사용하여 원 문장과 비교

from pykospacing import Spacing
spacing = Spacing()
kospacing_sent = spacing(new_sent)  # spacing함수를 이용해서 띄워쓰기를 새로 만들어라..

print(sent)
print(kospacing_sent)


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


[Korean Sentence Splitter]: AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x7fc548cf33b0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.


In [ ]:
#########################
# 텍스트 전처리
#########################
# 한국어 전처리 패키지(Text Preprocessing Tools for Korean Text) 추가!!!
# 4.  Py-Hanspell ==> 네이버 한글 "맞춤법 검사기"를 바탕으로 만들어진 패키지
###########################  ==> "정규표현식" 대신 사용

!pip3 install git+https://github.com/ssut/py-hanspell.git

from hanspell import spell_checker

sent = "맞춤법 틀리면 외 않되? 쓰고싶은대로쓰면돼지 "
spelled_sent = spell_checker.check(sent)

hanspell_sent = spelled_sent.checked
print(hanspell_sent)


  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-0knxcfs4
  Running command git clone -q https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-0knxcfs4
  Created wheel for py-hanspell: filename=py_hanspell-1.1-py3-none-any.whl size=4868 sha256=8449685b6e3a0b1da32daed8d2dbfd171099131d76f1279d34dc394e0c2c2a69
  Stored in directory: /tmp/pip-ephem-wheel-cache-s5r5oeqk/wheels/ab/f5/7b/d4124bb329c905301baed80e2ae45aa14e824f62ebc3ec2cc4
Successfully built py-hanspell
맞춤법 틀리면 왜 안돼? 쓰고 싶은 대로 쓰면 되지


In [ ]:
# 이 패키지는 띄어쓰기 또한 보정합니다. PyKoSpacing에 사용한 예제를 그대로 사용해봅시다

spelled_sent = spell_checker.check(new_sent)

hanspell_sent = spelled_sent.checked
print(hanspell_sent)
print(kospacing_sent) # 앞서 사용한 kospacing 패키지에서 얻은 결과

김철수는 극 중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연제(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.


In [ ]:
############### 드디어 "정수인코딩" ###################

In [ ]:
# dictionary 사용하기
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
# 문장 토큰화
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
# 기존의 텍스트 데이터가 문장 단위로 토큰화 된 것을 확인할 수 있습니다. 이제 정제 작업을 병행하며, 단어 토큰화를 수행합니다.

# 정제와 단어 토큰화
vocab = {}   # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i)   # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower()   # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words:   # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2:   # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
# vocab에는 중복을 제거한 단어와 각 단어에 대한 빈도수가 기록되어져 있습니다. vocab을 출력해보겠습니다.
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [ ]:
# 빈도수가 높은 순서대로 정렬
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [ ]:
# 이제 높은 빈도수를 가진 단어일수록 낮은 정수 인덱스를 부여
word_to_index = {}
i=0
for (word, frequency) in vocab_sorted :
    if frequency > 1 : # 정제(Cleaning) 챕터에서 언급했듯이 빈도수가 적은 단어는 제외한다.
        i=i+1
        word_to_index[word] = i
print(word_to_index)
# 1의 인덱스를 가진 단어가 가장 빈도수가 높은 단어

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
# 빈도수 상위 n개의 단어만 사용하고 싶다고하면 vocab에서 정수값이 1부터 n까지인 단어들만 사용하면 됩니다. 여기서는 상위 5개 단어만 사용한다고 가정한다.
vocab_size = 5
words_frequency = [w for w,c in word_to_index.items() if c >= vocab_size + 1] # 인덱스가 5 초과인 단어 제거
for w in words_frequency:
    del word_to_index[w]    # 해당 단어에 대한 인덱스 정보를 삭제
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
# word_to_index에는 빈도수가 높은 상위 5개의 단어만 저장되었습니다. 
# 이제 word_to_index를 사용하여 단어 토큰화가 된 상태로 저장된 sentences에 있는 각 단어를 정수로 바꾸는 작업을 하겠습니다.
# sentences에서 첫번째 문장은 ['barber', 'person']이었는데, 이 문장에 대해서는 [1, 5]로 인코딩합니다. 
# 그런데 두번째 문장인 ['barber', 'good', 'person']에는 더 이상 word_to_index에는 존재하지 않는 단어인 'good'이라는 단어가 있습니다.

# 이처럼 단어 집합에 존재하지 않는 단어들을 Out-Of-Vocabulary(단어 집합에 없는 단어)의 약자로 'OOV'라고 합니다. 
# word_to_index에 'OOV'란 단어를 새롭게 추가하고, 단어 집합에 없는 단어들은 'OOV'의 인덱스로 인코딩하겠습니다.

word_to_index['OOV'] = len(word_to_index) + 1

In [ ]:
# 이제 word_to_index를 사용하여 sentences의 모든 단어들을 맵핑되는 정수로 인코딩
encoded = []
for s in sentences:
    temp = []
    for w in s:
        try:
            temp.append(word_to_index[w])
        except KeyError:
            temp.append(word_to_index['OOV'])
    encoded.append(temp)
print(encoded)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [ ]:
#########################
# "Keras"의 텍스트 전처리
#########################
# 5.  정수 인코딩
#  keras에 있는 "Tokenizer"를 이용해서 빠르게 처리
###########################

# 단어에 정수를 부여하는 방법 ==> 단어를 빈도수 순으로 정렬한 단어 집합(vocabulary)을 만들고
#                                 빈도수가 높은 순서대로 차례로 낮은 숫자부터 정수를 부여하는 방법
# 케라스(Keras)는 기본적인 전처리를 위한 도구들을 제공합니다. 때로는 정수 인코딩을 위해서 케라스의 전처리 도구인 토크나이저를 사용하기도 한다!!

from tensorflow.keras.preprocessing.text import Tokenizer

# 불용어 처리까지 끝난 문장을 사용해야 한다!!
# sentences=[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'],
#           ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], 
#           ['barber', 'went', 'huge', 'mountain']]

# 한글의 경우를 보기위해서 sentences 내용을 한글 불용어처리된 자료를 사용
sentences=[['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.'],
           ['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']]


tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
# fit_on_texts는 입력한 텍스트로부터 단어 빈도수가 높은 순으로 낮은 정수 인덱스를 부여하는데,
# 정확히 앞서 설명한 정수 인코딩 작업이 이루어진다고 보면됩니다. 각 단어에 인덱스가 어떻게 부여되었는지를 보려면, "word_index"를 사용합니다.

print(tokenizer.word_index)



{'.': 1, '게': 2, '고기를': 3, '구우려고': 4, '안': 5, '돼': 6, '고기라고': 7, '다': 8, '같은': 9, '삼겹살을': 10, '구울': 11, '때는': 12, '중요한': 13, '있지': 14, '아무렇게나': 15, '하면': 16, '아니거든': 17, '예컨대': 18}


In [ ]:
# 각 단어의 빈도수가 높은 순서대로 인덱스가 부여된 것을 확인할 수 있습니다. 
# 각 단어가 카운트를 수행하였을 때 몇 개였는지를 보고자 한다면 word_counts를 사용합니다.(특정단어가 몇 개 등장했는지의 횟수)

print(tokenizer.word_counts)


OrderedDict([('고기를', 2), ('아무렇게나', 1), ('구우려고', 2), ('하면', 1), ('안', 2), ('돼', 2), ('.', 6), ('고기라고', 2), ('다', 2), ('같은', 2), ('게', 4), ('아니거든', 1), ('예컨대', 1), ('삼겹살을', 2), ('구울', 2), ('때는', 2), ('중요한', 2), ('있지', 2)])


In [ ]:
################################
# texts_to_sequences()는 입력으로 들어온 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환!!
################################

# 정수 인코딩된 list of list를 출력해라!!

print(tokenizer.texts_to_sequences(sentences))  
# "texts_to_sequences()"" 함수가 가장 중요!!! ===> 정수 인코딩 결과까지 출력

# sentences=[['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.'],
#           ['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']]


# 부여된 index ==> {'.': 1, '게': 2, '고기를': 3, '구우려고': 4, '안': 5, '돼': 6, '고기라고': 7, '다': 8, '같은': 9, '삼겹살을': 10, '구울': 11, 
#                       '때는': 12, '중요한': 13, '있지': 14,  '아무렇게나': 15, '하면': 16, '아니거든': 17, '예컨대': 18}

# sentences의 문자들을 각각의 index로 mapping해서 정수 인코딩의 결과값을 출력한다!!!


[[3, 15, 4, 16, 5, 6, 1, 7, 8, 9, 2, 17, 1, 18, 10, 11, 12, 13, 2, 14, 1], [3, 4, 5, 6, 1, 7, 8, 9, 2, 1, 10, 11, 12, 13, 2, 14, 1]]


In [ ]:
# ***********************************************************************
# 원-핫 인코딩 

# sub_text="점심 먹으러 갈래 메뉴는 햄버거 최고야"
# encoded=t.texts_to_sequences([sub_text])[0]
# print(encoded)      ==>    결과    ==>  [2, 5, 1, 6, 3, 7]

# 케라스는 정수 인코딩 된 결과로부터 원-핫 인코딩을 수행하는 to_categorical()를 지원
# one_hot = to_categorical(encoded)
# print(one_hot)
#  ==>  결과값
#  [[0. 0. 1. 0. 0. 0. 0. 0.]   # 인덱스 2의 원-핫 벡터
#  [0. 0. 0. 0. 0. 1. 0. 0.]    # 인덱스 5의 원-핫 벡터
#  [0. 1. 0. 0. 0. 0. 0. 0.]    # 인덱스 1의 원-핫 벡터
#  [0. 0. 0. 0. 0. 0. 1. 0.]    # 인덱스 6의 원-핫 벡터
#  [0. 0. 0. 1. 0. 0. 0. 0.]    # 인덱스 3의 원-핫 벡터
#  [0. 0. 0. 0. 0. 0. 0. 1.]]   # 인덱스 7의 원-핫 벡터
########################################################
# 위의 결과는 "점심 먹으러 갈래 메뉴는 햄버거 최고야"라는 문장이 [2, 5, 1, 6, 3, 7]로 정수 인코딩이 되고나서, 
# 각각의 인코딩 된 결과를 인덱스로 원-핫 인코딩이 수행된 모습을 보여줍니다.
# **************************************************************************

In [ ]:
# 케라스(Keras)를 이용한 원-핫 인코딩(One-Hot Encoding)
# 자연어 처리에서는 문자를 숫자로 바꾸는 여러가지 기법들이 있는데... "원-핫 인코딩(One-Hot Encoding)"은 그 많은 기법 중에서 단어를 표현하는 가장 기본적인 표현 방법

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical    #  케라스는 원-핫 인코딩을 수행하는 유용한 도구 to_categorical()를 지원

text="나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

t = Tokenizer()
t.fit_on_texts([text])
print(t.word_index)  # 각 단어에 대한 인코딩 결과 출력.
# 빈도수가 높은 단어가 낮은 인덱스 부여..


{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [ ]:
# texts_to_sequences()를 통해서 이를 정수 시퀀스로 변환가능합니다. 
# 생성된 단어 집합 내의 일부 단어들로만 구성된 서브 텍스트인 sub_text를 만들어 확인해보면..

sub_text="점심 먹으러 갈래 메뉴는 햄버거 최고야"

# {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}
encoded=t.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 5, 1, 6, 3, 7]


In [ ]:
# 케라스는 정수 인코딩 된 결과로부터 원-핫 인코딩을 수행하는 to_categorical()를 지원

one_hot = to_categorical(encoded)  # to_categorical함수를 이용해서 "원 핫 인코딩" 작업을 해준다!!!
print(one_hot)


[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# **************************************
# 카운트 기반의 단어 표현(Count based word Representation)
# **************************************
# TF-IDF(Term Frequency-Inverse Document Frequency) ==> DTM 내에 있는 각 단어에 대한 중요도를 계산할 수 있는 TF-IDF 가중치에 대해서 알아보도록 한다.

In [ ]:
# TF-IDF(Term Frequency-Inverse Document Frequency) ==> DTM내의 각 단어에 대한 중요도를 계산

#  tf(d,t) : 특정 문서 d에서의 특정 "단어 t의 등장 횟수".
#  df(t) :  특정 단어 t가 등장한 "문서의 수".
#  idf(d, t) : df(t)에 반비례하는 수.

import pandas as pd     # 데이터프레임 사용을 위해
from math import log    # IDF 계산을 위해


In [ ]:
docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()


In [ ]:
N = len(docs) # 총 문서의 수

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
    return log(N/(df + 1))

def tfidf(t, d):
    return tf(t,d)* idf(t)


In [ ]:
result = []
for i in range(N): # 각 문서에 대해서 아래 명령을 수행
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]        
        result[-1].append(tf(t, d))

#   docs = [
#  '먹고 싶은 사과',
#  '먹고 싶은 바나나',
#  '길고 노란 바나나 바나나',
#  '저는 과일이 좋아요'
#   ] 

tf_ = pd.DataFrame(result, columns = vocab)
tf_


과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
# DTM이 완성되었습니다. 
# DTM에서 각 단어의 인덱스가 어떻게 부여되었는지를 확인하기 위해, 인덱스를 확인해보았습니다. 
# 첫번째 열의 경우에는 0의 인덱스를 가진 do입니다. do는 세번째 문서에만 등장했기 때문에, 
# 세번째 행에서만 1의 값을 가집니다. 두번째 열의 경우에는 1의 인덱스를 가진 know입니다. 
# know는 첫번째 문서에만 등장했기 때문에 첫번째 행에서만 1의 값을 가집니다.

In [ ]:
# 사이킷런은 TF-IDF를 자동 계산해주는 TfidfVectorizer를 제공

from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
#   이제 BoW, DTM, TF-IDF에 대해서 전부 학습했습니다. 문서들 간의 유사도를 구하기 위한 재료 손질하는 방법을 배운 셈입니다