<a href="https://colab.research.google.com/github/kmongsil1105/colab_ipynb/blob/main/AI_PyTorch(Tensor2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **  텐서 조작하기(Tensor Manipulation) 2  ** 

### 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요함!!
파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다. 

Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 합니다. 실습을 위해 우선 임의로 다음과 같이 3차원 텐서를 만든다

In [ ]:
import numpy as np
import torch

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)    

# torch.Size([2, 2, 3]) ==> 2 * 3 행렬이 옆으로 2개 나열되어 있는 형태!!!

torch.Size([2, 2, 3])


* 3차원 텐서에서 2차원 텐서로 변경 ==> ft 텐서를 view를 사용하여 크기(shape)를 2차원 텐서로 변경

In [ ]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


 * **view([-1, 3])이 가지는 의미**==> -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 
3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다. 
다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다. *결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.*



 * 내부적으로 크기 변환은 다음과 같이 이루어졌습니다. **(2, 2, 3) -> (2 × 2, 3) -> (4, 3)**

 * 규칙을 정리해봅시다. 

 * view는 기본적으로 **변경 전과 변경 후의 텐서 안의 원소의 개수가 유지**되어야 합니다.

 * 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

변경 전 텐서의 원소의 수는 (2 × 2 × 3) = 12개였습니다. 그리고 변경 후 텐서의 원소의 개수 또한 (4 × 3) = 12개였습니다.

******************************************

 *  **3차원 텐서의 크기 변경** ==>  3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보겠습니다. 
 
 view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 한다고 언급한 바 있습니다. 
 
 그렇다면 (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?


 * (2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다. 이를 실습으로 확인해봅시다.

In [ ]:
print(ft.view([-1, 1, 3]))         #     tensor([[ 0.,  1.,  2.],   ==> 변경전 tensor
print(ft.view([-1, 1, 3]).shape)   #             [ 3.,  4.,  5.],
                                   #             [ 6.,  7.,  8.],
                                   #             [ 9., 10., 11.]]) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


 * 스퀴즈(Squeeze) - 1인 차원을 제거한다.

 * 스퀴즈는 차원이 1인 경우에는 해당 차원을 제거합니다.
실습을 위해 임의로 (3 × 1)의 크기를 가지는 2차원 텐서를 만들겠습니다.

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


 * 해당 텐서는 (3 × 1)의 크기를 가집니다. 두번째 차원이 1이므로 squeeze를 사용하면 (3,)의 크기를 가지는 텐서로 변경됩니다.

In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


 * ******결과는 1이었던 두번째 차원이 제거되면서 (3,)의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을 알 수 있다.

-------------------------------------------------------

* 타입 캐스팅(Type Casting)

* 텐서에는 자료형이라는 것이 있습니다. 각 데이터형별로 정의되어져 있는데,    
* 32비트의 부동 소수점은 torch.FloatTensor를, 
* 64비트의 부호 있는 정수는 torch.LongTensor를 사용합니다.
 * **GPU 연산용 ==> "cuda.floatTensor"**

 * **CPU 연산용 ==> "torch.floatTensor"**

In [ ]:
# 실습을 위해 long 타입의 lt라는 텐서를 선언
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
# 텐서에다가 .float()를 붙이면 바로 float형으로 타입이 변경됩니다.
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
# 이번에는 Byte 타입의 bt라는 텐서를 만들어보겠습니다.
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


 * 여기에 .long()이라고하면 long 타입의 텐서로 변경되고 .float()이라고 하면 float 타입의 텐서로 변경됩니다.

In [ ]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


 ------------------------------------------------------------

 * 연결하기(concatenate)

 이번에는 두 텐서를 연결하는 방법에 대해서 알아보겠습니다.
우선 (2 × 2) 크기의 텐서를 두 개 만듭니다.

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])  # 2 * 2
y = torch.FloatTensor([[5, 6], [7, 8]])  # 2 * 2 
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


 * 두 텐서를 torch.cat([ ])를 통해 연결해보겠습니다. 
 
  그런데 연결 방법은 한 가지만 있는 것이 아닙니다. 
  
  torch.cat은 어느 차원을 늘릴 것인지를 인자로 줄 수 있습니다. ==> "**dim=0**" 은 첫번째 차원을 늘리라는 의미를 담고있습니다.

In [ ]:
print(torch.cat([x, y], dim=0))    # 4 * 2 로 연결해서 변경!!!
#   dim=0을 인자로 했더니 두 개의 (2 × 2) 텐서가 (4 × 2) 텐서가 된 것을 볼 수 있습니다. 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


 * 이번에는 dim=1을 인자로 주겠습니다.

In [ ]:
print(torch.cat([x, y], dim=1))    # 2 * 4 로 연결해서 변경!!!

# dim=1을 인자로 했더니 두 개의 (2 × 2) 텐서가 (2 × 4) 텐서가 된 것을 볼 수 있습니다.

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


 * 딥 러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 
 
 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있습니다.


 ----------------------------------------------------------------

 * ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])  # 2 * 3 텐서
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


 * 위 텐서에 ones_like를 하면 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성

In [ ]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


 * 위 텐서에 zeros_like를 하면 동일한 크기(shape)지만 0으로만 값이 채워진 텐서를 생성합니다.

In [ ]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])
