<a href="https://colab.research.google.com/github/kmongsil1105/colab_ipynb/blob/main/AI_Pytorch_tensor_%EC%A1%B0%EC%9E%91%ED%95%98%EA%B8%B01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다. 
# 끝 번호에 해당하는 것은 포함하지 않습니다.

t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [ ]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱 # 끝 번호에 해당하는 것은 포함하지 않습니다.
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


2D with PyTorch

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
# 서에서 두번째 열에 있는 모든 값을 가져온 상황입니다
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t[:, :-1]) 
# 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


 * 브로드캐스팅(Broadcasting) :: 두 행렬이 곱셈을 할 때에는 A의 마지막 차원과 B의 첫번째 차원이 일치해야합니다.

   파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공

In [ ]:
# 같은 크기일 때 연산을 하는 경우를 보겠습니다.
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
#[1, 2]
#==> [[1, 2],
#     [1, 2]]
#[3]
#[4]
#==> [[3, 3],
#     [4, 4]]

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print('m1 : ',m1)
print('m2 : ',m2)
print('------------------')
print('m1.matmul(m2)')
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
m1 :  tensor([[1., 2.],
        [3., 4.]])
m2 :  tensor([[1.],
        [2.]])
------------------
m1.matmul(m2)
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1)
print(m2)
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print('(m1 * m2)')
print(m1 * m2) # 2 x 2
print('m1.mul(m2)')
print(m1.mul(m2))
# 서로 다른 크기의 행렬이 브로드캐스팅이 된 후에 element-wise 곱셈이 수행되는 것을 보여줍니다
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
#[1]
#[2]
#==> [[1, 1],
#     [2, 2]]

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
(m1 * m2)
tensor([[1., 2.],
        [6., 8.]])
m1.mul(m2)
tensor([[1., 2.],
        [6., 8.]])


 * 평균(Mean)

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean()) # 원소 4개(1,2,3,4)의 평균

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [ ]:
print(t)
print('-------------------')
print(t.mean(dim=0)) # dim=0이라는 것은 첫번째 차원을 의미합니다. 행렬에서 첫번째 차원은 '행'을 의미
                     # 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다. 다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다. 
                     # 기존 행렬의 크기는 (2, 2)였지만 이를 수행하면 열의 차원만 보존되면서 (1, 2)가 됩니다. 이는 (2,)와 같으며 벡터입니다
# 실제 연산 과정
#t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

#[[1., 2.],
# [3., 4.]]

#1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
#결과 ==> [2., 3.]

tensor([[1., 2.],
        [3., 4.]])
-------------------
tensor([2., 3.])


이번에는 인자로 dim=1을 주겠습니다. 이번에는 두번째 차원을 제거합니다. 즉, 열이 제거된 텐서가 되어야 합니다.

In [ ]:
print(t)                              
print('-------------------')
print(t.mean(dim=1))
# 열의 차원이 제거되어야 하므로 (2, 2)의 크기에서 (2, 1)의 크기가 됩니다. 
# 이번에는 1과 3의 평균을 구하고 3과 4의 평균을 구하게 됩니다.

tensor([[1., 2.],
        [3., 4.]])
-------------------
tensor([1.5000, 3.5000])


==>  (2 × 1)은 결국 1차원이므로 (1 × 2)와 같이 표현되면서 위와 같이 [1.5, 3.5]로 출력

* 덧셈(Sum)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


 * 최대(Max)와 아그맥스(ArgMax) :: 최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


In [ ]:
print(t.max(dim=0)) # Returns two values: max and argmax(첫번째 차원을 제거한다는 의미)

# [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.

#[[1, 2],
# [3, 4]]
#첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
#두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
#다시 말해 3과 4의 인덱스는 [1, 1]입니다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


 * 0번 인덱스를 사용하면 max 값만 받아올 수 있고, 1번 인덱스를 사용하면 argmax 값만 받아올 수 있습니다.

In [ ]:
print(t)
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

tensor([[1., 2.],
        [3., 4.]])
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


훈련 데이터 하나의 크기를 256이라고 해봅시다. [3, 1, 2, 5, ...] 이런 숫자들의 나열이 256의 길이로 있다고 상상하면됩니다. 

 * 다시 말해 훈련 데이터 하나 = 벡터의 차원은 256입니다. 

만약 이런 훈련 데이터의 개수가 3000개라고 한다면, 현재 전체 훈련 데이터의 크기는 3,000 × 256입니다. 행렬이니까 2D 텐서. 

3,000개를 1개씩 꺼내서 처리하는 것도 가능하지만 컴퓨터는 훈련 데이터를 하나씩 처리하는 것보다 보통 덩어리로 처리합니다. 

3,000개에서 64개씩 꺼내서 처리한다고 한다면 이 때 batch size를 64라고 합니다.

*  그렇다면 컴퓨터가 한 번에 처리하는 2D 텐서의 크기는 (batch size × dim) = 64 × 256입니다.