<a href="https://colab.research.google.com/github/kmongsil1105/colab_ipynb/blob/main/AI_tensor%EC%A1%B0%EC%9E%91%ED%95%98%EA%B8%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서 조작하기(Tensor Manipulation) 2

 * 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요함!!

In [ ]:
import torch
import numpy as np

In [ ]:
# 파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다. 
# Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


 * 3차원 텐서에서 2차원 텐서로 변경 :: "view"를 사용하여 크기(shape)를 2차원 텐서로 변경해봅시다.

In [ ]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
# -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)

view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다

 * 3차원 텐서의 크기 변경

In [ ]:
#  (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?
#  (2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다
print(ft) 
print(ft.shape)
print('---------------------------')
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
--------------------
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


 * 스퀴즈(Squeeze) - 차원이 1인 경우에는 해당 차원을 제거

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
# 두번째 차원이 1이므로 squeeze를 사용하면 (3,)의 크기를 가지는 텐서로 변경됩니다.
# 차원이 1인 경우에는 해당 차원을 제거
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


결과는 1이었던 두번째 차원이 제거되면서 (3,)의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을 보여줍니다.

 * 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


 차원이 1개인 1차원 벡터입니다

In [ ]:
# 첫번째 차원의 인덱스를 의미하는 숫자 0을 인자로 넣으면 "첫번째 차원에 1인 차원이 추가"됩니다.
print(ft)
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([0., 1., 2.])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


 위 결과는 (3,)의 크기를 가졌던 1차원 벡터가 (1, 3)의 2차원 텐서로 변경된 것을 보여줍니다.

In [ ]:
print(ft)
print(ft.view(1, -1))
print(ft.view(1, -1).shape)
# unsqueeze와 view가 동일한 결과를 만든 것을 보여줍니다

tensor([0., 1., 2.])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft)   # 1*3
print(ft.unsqueeze(1))  # 두번째 차원에 1을 추가하겠다는 것을 의미
print(ft.unsqueeze(1).shape)  # 3*1

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# view( ), squeeze( ), unsqueeze( )는 

# 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절합니다.

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())     # long 타입의 텐서로 변경
print(bt.float())    # float 타입의 텐서로 변경

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


 * 연결하기(concatenate)

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print(y)
print('-----------------------')
print(torch.cat([x, y]))
# torch.cat은 어느 차원을 늘릴 것인지를 인자로 줄 수 있습니다. 
# dim=0은 첫번째 차원(행:2차원 텐서이므로)을 늘리라는 의미를 담고있습니다.
print(torch.cat([x, y], dim=0))
print('-----------------------')
print(torch.cat([x, y], dim=1))
# dim=1은 두번째 차원(열:2차원 텐서이므로)을 늘리라는 의미를 담고있습니다.

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
-----------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
-----------------------
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


 * 스택킹(Stacking)

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
# torch.stack을 통해서 3개의 벡터를 모두 스택킹해보겠습니다.
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


 3개의 벡터가 순차적으로 쌓여 (3 × 2) 텐서가 된 것을 보여줍니다.

In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # 위쪽 stack기능과 같은 작업

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


 x, y, z는 기존에는 전부 (2,)의 크기를 가졌습니다. 
 
 그런데 .unsqueeze(0)을 하므로서 3개의 벡터는 전부 (1, 2)의 크기의 2차원 텐서로 변경됩니다. 
 
 여기에 연결(concatenate)를 의미하는 cat을 사용하면 (3 x 2) 텐서가 됩니다.

In [ ]:
print(torch.stack([x, y, z], dim=1))  # 두번째 차원이 증가하도록 쌓으라는 의미

tensor([[1., 2., 3.],
        [4., 5., 6.]])


 * ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
# ones_like를 하면 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성합니다
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


 * In-place Operation (덮어쓰기 연산)

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


그런데 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.



In [ ]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
